# Generated by Django 4.1.7 on 2023-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='waterpredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.DecimalField(decimal_places=7, max_digits=15)),
                ('humidity', models.IntegerField()),
                ('soilMoisture', models.IntegerField()),
                ('waterLevel', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'WaterPredictions',
            },
        ),
    ]
